### ISSUE TITLE
This API version is not supported

### ISSUE THREAD

**Issue by sjfm-design** [stephan1827/ioBroker.srm#4]
**Describe the bug**  
Synology RT2600AC Wireless Router 
3x Synology Mesh Router MR2200ac

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
![grafik](https://github.com/stephan1827/ioBroker.srm/assets/30467409/958ad676-8da8-4715-a188-ec168f084a12)

<html><body>

srm.0 | 2023-12-26 12:57:27.734 | error | Error: This API version is not supported
-- | -- | -- | --
srm.0 | 2023-12-26 12:56:27.870 | error | Error: This API version is not supported
srm.0 | 2023-12-26 12:55:42.761 | error | Error: This API version is not supported
srm.0 | 2023-12-26 12:54:42.998 | error | Error: This API version is not supported
srm.0 | 2023-12-26 12:53:42.847 | error | Error: This API version is not supported
srm.0 | 2023-12-26 12:52:42.854 | error | Error: This API version is not supported
srm.0 | 2023-12-26 12:51:42.966 | error | Error: This API version is not supported
srm.0 | 2023-12-26 12:50:42.872 | error | Error: This API version is not supported
srm.0 | 2023-12-26 12:49:42.958 | error | Error: This API version is not supported
srm.0 | 2023-12-26 12:48:23.859 | error | Credentials must be provided for 192.168.0.1

**Versions:**  
 - Adapter version: 0.1.5
 - JS-Controller version: latest
 - Node version: latest
 - Operating system: latest

**Additional context**

**Comment by stephan1827** [comment]
Can you please try version 0.1.6.

![image](https://github.com/stephan1827/ioBroker.srm/assets/2972703/2235ef88-4772-4084-8bc5-6df5d652eba6)

Make sure version is up to date and then hit upload to make sure the instance is updated, to0.

**Comment by stephan1827** [comment]
Fixed in release 0.2.0

**Comment by stephan1827** [comment]
Fixed in release 0.2.0
